const shopActionTypes = {
  FETCH_OFFERS_START: 'FETCH_OFFERS_START',
  FETCH_OFFERS_SUCCESS: 'FETCH_OFFERS_SUCCESS',
  FETCH_OFFERS_FAILURE: 'FETCH_OFFERS_FAILURE'
};

export default shopActionTypes;
